### PR TITLE
Fixed previous merge conflict, adding phish tank information

### PR DESCRIPTION
**Pull request by lem0w**
There was a previous merge conflict that has been fixed. Adding information for phish tank
https://phishtank.org/developer_info.php

### CODE REVIEW

**Comment by Bert-JanP** [comment]
When opening the links I get the following error:

`You have exceeded the request rate limit for this method. Please see the response headers for usage stats. For more information about rate limiting on Phishtank, please see our developer site: http://www.phishtank.com/developer_info.php `

Are you able to open the links?

**Comment by lem0w** [comment]
> When opening the links I get the following error:
> 
> `You have exceeded the request rate limit for this method. Please see the response headers for usage stats. For more information about rate limiting on Phishtank, please see our developer site: http://www.phishtank.com/developer_info.php `
> 
> Are you able to open the links?

Hi, yeah I get the same error when trying to open the xml one and php. However, if you need to access the record it is better to only use the CSV link http://data.phishtank.com/data/online-valid.csv , both json and csv would work without issues with sentinel when querying either url

**Comment by lem0w** [comment]
Let me know if you want me to remove that ones that can't be accessed via the browser, so that way only the csv will be listed. While the other ones I can just put the link to their main page in case anyone want to look at the other types.

**Comment by lem0w** [comment]
I removed the other links that can't be accessed via the browser or download. So it is now only the CSV file.

**Comment by Bert-JanP** [comment]
Also with the CVS file I do get errors. Phishtanks states the following:

`If you'll be doing lots of lookups, the best option is to take advantage of our downloadable databases. Available in multiple formats and updated hourly, these make it easy to have fast and up to date phishing detection built into your application.

The data is available in a variety of formats to make it as easy as possible for you to implement. We're always open to suggestions for additional formats we could provide, so if you have any thoughts, please join our [developers list](https://phishtank.org/mailing_lists.php) and let us know!

If you do intend to fetch these files automatically, please [register for an application key](https://phishtank.org/api_register.php) and see below for instructions on how to use it to request files. Without this key, you will be limited to a few downloads per day.`

It has the be always open to being on this list, therefore I will close the PR. They also do not add additional users which could request a key at this moment. It would definitely be a addition if they had a list which could always be downloaded.

**Pull request closed without merging**
